---
- name: Create Users
  user:
    append: "{{ item.append | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    hidden: "{{ item.hidden | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    local: "{{ item.local | default(omit) }}"
    login_class: "{{ item.login_class | default(omit) }}"
    move_home: "{{ item.move_home | default(omit) }}"
    name: "{{ item.name }}"
    non_unique: "{{ item.non_unique | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    password_lock: "{{ item.password_lock | default(omit) }}"
    profile: "{{ item.profile | default(omit) }}"
    remove: "{{ item.remove | default(omit) }}"
    role: "{{ item.role | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    skeleton: "{{ item.skeleton | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ item.ssh_key_comment | default(omit) }}"
    ssh_key_file: "{{ item.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ item.ssh_key_type | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default(false) }}"
    uid: "{{ item.uid | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ user_list }}"

- name: Added User ssh keys
  authorized_key:
    comment: "{{ item.1.comment | default(omit) }}"
    exclusive: "{{ item.1.exclusive | default(omit) }}"
    follow: "{{ item.1.follow | default(omit) }}"
    key: "{{ item.1.key }}"
    key_options: "{{ item.1.key_options | default(omit) }}"
    manage_dir: "{{ item.1.manage_dir | default(omit) }}"
    path: "{{ item.1.path | default(omit) }}"
    state: "{{ item.1.state | default(omit) }}"
    user: "{{ item.0.name }}"
    validate_certs: "{{ item.1.validate_certs | default(omit) }}"
  loop: "{{ q('ansible.builtin.subelements', user_list, 'ssh_key', {'skip_missing': True}) }}"
